#' Plots a basic Kaplan-Meier plot
#'
#' This function makes a ggplot version of a kaplan-Meier plot. It is a wrapper for ggSimpleSurv, with the addition of some basic ggplot formatting. If you wish to do the formatting yourself, then use ggSimpleSurv. This function is designed to be standalone and resembles the base R plotting more than the ggplot paradigm.
#'
#' @param srv A vector of survival time class "Surv" as generated by the Surv function.
#' @param Factor A character or factor vector to split the data.
#' @param showCI boolean value, show the 95% confidance intervail as calculated by survfit
#'
#' @return Returns a ggplot object.
#' @import ggplot2
#' @export
#' @examples
#' srv <- Surv(c(rchisq(1000,3)*10,
#' rchisq(1000,5)*10),
#' c(rbinom(1000,1,.9),
#'   rbinom(1000,1,.9)))
#' X <- rep(c('A','B'),each=1000)
#' Plt <- ggPrettySurv(srv,X)
#' Plt

ggPrettySurv <- function(srv,Factor=NULL,showCI=T,
                         Main=NULL,xlab='Time',ylab='Survival',
                         LineSize=.8){
  frm <- survForm(srv,Factor)

  # Generate the basic plot
  if(is.null(Factor)){
    Plt <- ggplot(frm,aes(x=time,y=surv))
  } else{
    Plt <- ggplot(frm,aes(x=time,y=surv,color=Group,group=Group))
  }
  Plt <- Plt +
    geom_step(size=LineSize)+
    geom_point(data= filter(frm,n.censor >0),shape='|',size=4)

  # add confidence intervals
  if(showCI){
    Plt <- Plt +
      geom_step(aes(y=lower),linetype='dashed',na.rm=T)+
      geom_step(aes(y=upper),linetype='dashed',na.rm=T)
  }

  Plt <- Plt +
    scale_y_continuous(limits = c(0,1.03),expand=c(0,0)) +
    scale_x_continuous(limits = c(0,max(frm$time)*1.03),expand=c(0,0)) +
    ggtitle(Main) +
    theme_bw() +
    theme(legend.position ='bottom') +
    ylab(ylab)+xlab(xlab)+
    scale_color_brewer(palette = 'Set1')

  return(Plt)
}
