#' Plots a basic Kaplan-Meier plot
#'
#' A very quick basic function for people with a general understanding of ggplot who want to format the plot themselves. See also ggPrettySurv, a wrapper for this function which also sets some of the ggplot themes to something more attractive than the basic.
#'
#' @param srv A vector of survival time class "Surv" as generated by the Surv function.
#' @param Factor A character or factor vector to split the data.
#' @param showCI boolean value, show the 95% confidance intervail as calculated by survfit
#'
#' @return Returns a ggplot object.
#' @import ggplot2
#' @export
#' @examples
#' srv <- Surv(c(rchisq(1000,3)*10,
#' rchisq(1000,5)*10),
#' c(rbinom(1000,1,.9),
#'   rbinom(1000,1,.9)))
#' X <- rep(c('A','B'),each=1000)
#' Plt <- ggSimpleSurv(srv,X)
#' Plt
#' # This object can be combine with standard ggplot options
#' Plt +
#' theme_bw()+
#' ggtile('Plot Title!")

ggSimpleSurv <- function(srv,Factor=NULL,showCI=T){
  frm <- survForm(srv,Factor)

  # Generate the basic plot
  if(is.null(Factor)){
    Plt <- ggplot(frm,aes(x=time,y=surv))
  } else{
    Plt <- ggplot(frm,aes(x=time,y=surv,color=Group,group=Group))
  }
  Plt <- Plt +
    geom_step()+
    geom_point(data= filter(frm,n.censor >0),shape='|',size=4)

  # add confidence intervals
  if(showCI){
    Plt <- Plt +
      geom_step(aes(y=lower),linetype='dashed',na.rm=T)+
      geom_step(aes(y=upper),linetype='dashed',na.rm=T)
  }
  return(Plt)
}
